# yaml-language-server: $schema=https://github.com/epics-containers/ioc-motorsim/releases/download/2024.9.1/ibek.ioc.schema.json

ioc_name: "{{ _global.get_env('IOC_NAME') }}"

description: REPLACE WITH DESCRIPTION

entities:
  - type: epics.EpicsEnvSet
    name: EPICS_TZ
    value: GMT0BST

  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  - type: motorSim.simMotorController
    controllerName: sim-controller1
    numAxes: 4 
    P: "XF:11BMB-ES{Chm:Smpl-Ax:"

  - type: motorSim.simMotorAxis
    controller: sim-controller1
    ADDR: 1 
    M: X}Mtr
    DESC: Motor X
    home: 1

  - type: motorSim.simMotorAxis
    controller: sim-controller1
    ADDR: 2 
    M: Z}Mtr
    DESC: Motor Z
    home: 1

  - type: motorSim.simMotorAxis
    controller: sim-controller1
    ADDR: 3 
    M: theta}Mtr
    DESC: Motor theta
    home: 1

  - type: motorSim.simMotorController
    controllerName: sim-controller2
    numAxes: 4 
    P: "XF:11BMB-ES{BS-Ax:"

  - type: motorSim.simMotorAxis
    controller: sim-controller2
    ADDR: 1 
    M: X}Mtr
    DESC: Motor X
    home: 1

  - type: motorSim.simMotorAxis
    controller: sim-controller2
    ADDR: 2 
    M: Y}Mtr
    DESC: Motor Y
    home: 1

  - type: motorSim.simMotorAxis
    controller: sim-controller2
    ADDR: 3 
    M: Phi}Mtr
    DESC: Motor phi
    home: 1
